## 1.1 Numpy
### 1.2.1 Пример
***Задача:*** Создать массив 5х2. Создать массив 5х2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [ ]:
import numpy as np
import math
x = np.array([[1,2],[3,4],[5,6],[7,9],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  9]
 [ 9 10]]
9
[3 4]

### 1.2.2 Пример
***Задача:***
Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [6]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5 5 5 5 5 5 5 5 5 5]
 [10 11 12 13 14 15 16 17 18 19]

### 1.2.3 Пример
***Задача:*** Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

In [7]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.01762665302191624 0.9934393383958551 0.5001393696082106

### 1.2.4 Пример
***Задача:*** Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [8]:
A = np.arange(25).reshape(5, 5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

### 1.2.5 Пример
***Задача:*** Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [11]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False

### 1.2.6 Пример
***Задача:*** отсортировать массив

In [12]:
arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]

### 1.3.1 Задание
***Задача:***
Создать матрицу 8х8 и заполнить ее в шахмотном порядке нулями и еденицами.

In [17]:
A = np.zeros((4,4), dtype=int)
A[::2, ::2] = 1
A[1::2,1::2] = 1
print(A)

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]

### 1.3.2 Задание
***Задача:*** Создать 5х5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [ ]:
A = np.tile(np.arange(5), (5, 1))
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

### 1.3.4 Задание
***Задача:*** Создать матрицу с 0 внутри, и 1 на границах.

In [30]:
m_size = 5
A = np.ones((m_size, m_size), dtype=int)
A[1:-1, 1:-1] = 0
print (A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

### Задание 1.3.3
***Задача:*** Создать массив 3x3x3 со случайными значениями.

In [35]:
A = np.random.default_rng().random((3,3,3))
print (A)

[[[0.68683342 0.63587359 0.55800209]
  [0.57228965 0.89346077 0.66792677]
  [0.50765075 0.68384803 0.44767724]]

 [[0.59099931 0.95695934 0.97634666]
  [0.06212941 0.19750429 0.39237199]
  [0.30547822 0.09667536 0.878443  ]]

 [[0.75105195 0.93123553 0.24514441]
  [0.73588551 0.70975484 0.27498351]
  [0.06511723 0.260207   0.19109493]]]

### Задание 1.3.5
***Задача:*** Создайте массив и отсортируйте его по убыванию.

In [38]:
arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr)[::-1])

[8 7 6 5 4 3 2 1]

### 1.3.5 Задание
***Задача:*** Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
A = np.random.default_rng().random((3,3))
print(A.shape, "\n", A.size, "\n", A.ndim)

(3, 3)
 9
 2

## 2 Dataframe
### 2.2.1 Пример
***Задача:*** Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

In [46]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])
print (lst,"\n",pd.Series(lst))
print(d, "\n", pd.Series(d))
print(ndarr, "\n", pd.Series(ndarr, index=['a', 'b', 'c', 'd', 'e']))

[1, 2, 3, 4, 5]
 0    1
1    2
2    3
3    4
4    5
dtype: int64
{'a': 1, 'b': 2, 'c': 3}
 a    1
b    2
c    3
dtype: int64
[1 2 3 4 5]
 a    1
b    2
c    3
d    4
e    5
dtype: int64

### Пример 2.2.2
***Задача:*** Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [48]:
s1 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64

### 2.2.3 Пример
***Задача:*** Создайте новый фрейм данных

In [49]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

                Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

### 2.2.4 Пример
Задача: загрузите фрейм данных по ссылке: https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [54]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### 2.2.5 Пример
Проанализировать характеристики фрейма данных.

Одна из самых простых вещей, которые мы можем сделать после загрузки данных, - это взглянуть на первые несколько строк с помощью модуля head. На последние строки можно посмотреть с помощью функции tail. Мы также можем вглянуть на количество строк и столбцов: dataframe.shape. Кроме того, используя метод describe, мы может получить описательную статистику для любых числовых стобцов.

In [55]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### 2.2.6 Пример
Выберите индивидуальные данные или срезы фрейма данных.

In [56]:
dataframe.iloc[1:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

### 2.2.7 Пример
Требуется отобрать строки фрейма данных на основе некоторого условия. Необхоидмо сформировать новый фрейм данных из пассажиров первого класса.

In [65]:
dataframe[dataframe['Pclass'] == '2'].head(2)

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

### 2.3.1 Задание
***Задача:*** Найдите евклидово расстояние между двумя Series (точками) a и b, не использу встроенную формулу.

In [69]:
import math
a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([4, 5, 6, 7, 8])
print(math.sqrt(pow((a - b),2).sum()))

6.708203932499369

### 2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных

In [70]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### 2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных, те же действия, что и в примерах 2.2.5-2.2.7

In [78]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

dataframe.iloc[1:4]

dataframe[dataframe['Pclass'] == 1.0].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

## 3. Нормализация
### 3.2.1 Пример
***Задача:*** Прошкладируйте числовой признак в диапазон между двумя значениями

In [83]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [909.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0,1))

sclaed_feature = minmax_scale.fit_transform(feature)
sclaed_feature

array([[0.        ],
       [0.28389109],
       [0.35486387],
       [0.42583664],
       [1.        ]])

### 3.2.2 Пример
***Задача:*** Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.

In [84]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized

print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0

### 3.2.3 Пример
***Задача:***
Дан фрейм данных
``` 
    dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
    'B':[103.02,107.26,110.35,114.23,114.68],
    'C':['big','small','big','small','small']})
```
Необходимо масштабировать его числовые столбцы.

In [89]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']})
print(dfTest)
dfTest[['A','B']] = scaler.fit_transform(dfTest[['A','B']])
dfTest

       A       B      C
0  14.00  103.02    big
1  90.20  107.26  small
2  90.95  110.35    big
3  96.27  114.23  small
4  91.21  114.68  small

          A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

### 3.3.2 Задание
Задача: Загрузить фрейм данных по ссылке https://raw.githubusercontent.com/akmand/datasets/master/iris.csv
Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [100]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)
print(dataframe[['sepal_length_cm']])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))
sclaed_feature = minmax_scale.fit_transform(dataframe[['sepal_length_cm']])
sclaed_feature
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(dataframe[['sepal_width_cm']])
standardized
print("Среднее:", round(standardized.mean(), 4))
print("Стандартное отклонение:",round(standardized.std()))

     sepal_length_cm
0                5.1
1                4.9
2                4.7
3                4.6
4                5.0
..               ...
145              6.7
146              6.3
147              6.5
148              6.2
149              5.9

[150 rows x 1 columns]
Среднее: -0.0
Стандартное отклонение: 1